// IAM runtime facade over the broader legacy API object.
// This isolates the standalone method pick-list from state and type layers.
import { idpApi as compatIdpApi } from './legacyApi'

const standaloneIdpApiMethodNames = [
  'acceptIamAccountOrganizationInvitation', 'approveIamAccountDelegatedConsentRequest',
  'beginIamMfaEnrollment', 'beginIamPasskeyLogin', 'beginIamWebAuthnRegistration',
  'cancelIamAccountDelegatedConsentRequest', 'changeIamAccountPassword', 'clearIamUserLockout',
  'completeIamPasskeyLogin', 'completeIamRequiredActions', 'completeIamWebAuthnRegistration',
  'confirmIamEmailVerification', 'confirmIamPasswordReset', 'continueIamAuthorizationRequest',
  'continueIamSamlAuthRequest', 'createIamAdminPermission', 'createIamAdminPolicy',
  'createIamAuthExecution', 'createIamAuthFlow', 'createIamAuthorizationPermission',
  'createIamAuthorizationPolicy', 'createIamBackup', 'createIamClient', 'createIamClientPolicy',
  'createIamClientScope', 'createIamDelegatedAdmin', 'createIamDeviceAuthorization',
  'createIamExtension', 'createIamExtensionBinding', 'createIamExtensionProvider',
  'createIamGroup', 'createIamIdentityProvider', 'createIamOrganization',
  'createIamOrganizationInvitation', 'createIamOrganizationMembership',
  'createIamProtectedResource', 'createIamProtectedScope', 'createIamProtocolMapper',
  'createIamPushedAuthorizationRequest', 'createIamRealm', 'createIamRealmAttribute', 'createIamResourceServer',
  'createIamRole', 'createIamUser', 'createIamUserFederationProvider',
  'denyIamAccountDelegatedConsentRequest', 'disableIamMfa', 'dynamicallyRegisterIamClient',
  'evaluateIamAuthorization', 'exportIamRealm', 'getAuthSession', 'getIamAccountProfile',
  'getIamAccountSecurity', 'getIamAccountSession', 'getIamAuthorizationRequest',
  'getIamBenchmarkCatalog', 'getIamBootstrapPackage', 'getIamDeploymentProfile',
  'getIamDifferentiationReview', 'getIamExtensionSummary', 'getIamFormalReview',
  'getIamHealthSummary', 'getIamInteroperabilityReview', 'getIamOidcDiscovery',
  'getIamOperationsDiagnostics', 'getIamOperationsSummary', 'getIamPublicCatalog',
  'getIamReadinessReview', 'getIamRealmExperience', 'getIamRecoveryProfile',
  'getIamReviewSummary', 'getIamSamlAuthRequest', 'getIamSecuritySummary',
  'getIamStandardsMatrix', 'getIamSummary', 'getIamUserLoginHistory',
  'getIamUserSecuritySummary', 'getIamValidationSummary', 'getPlatformCapabilities',
  'getTenantContext', 'grantIamAccountDelegatedConsent', 'grantIamConsent', 'introspectIamToken',
  'issueIamInitialAccessToken', 'issueIamToken', 'listIamAccountConsents',
  'listIamAccountDelegatedConsentRequests', 'listIamAccountDelegatedConsents',
  'listIamAccountDelegatedRelationships', 'listIamAccountLinkedIdentities',
  'listIamAccountOrganizations', 'listIamAccountSessions', 'listIamAccountWebAuthnCredentials',
  'listIamAdminEvaluations', 'listIamAdminPermissions', 'listIamAdminPolicies',
  'listIamAuthExecutions', 'listIamAuthFlowBindings', 'listIamAuthFlows',
  'listIamAuthorizationEvaluations', 'listIamAuthorizationPermissions',
  'listIamAuthorizationPolicies', 'listIamBackups', 'listIamClientPolicies',
  'listIamClientScopes', 'listIamClients', 'listIamDelegatedAdmins',
  'listIamDeviceAuthorizations', 'listIamExtensionBindings', 'listIamExtensionProviders',
  'listIamExtensions', 'listIamFederationEvents', 'listIamFederationSyncJobs', 'listIamGroups',
  'listIamIdentityProviders', 'listIamInitialAccessTokens', 'listIamIssuedTokens',
  'listIamLinkedIdentities', 'listIamNotificationDeliveries', 'listIamNotificationTemplates',
  'listIamOrganizationInvitations', 'listIamOrganizationMemberships', 'listIamOrganizations',
  'listIamPermissionTickets', 'listIamProtectedResources', 'listIamProtectedScopes',
  'listIamProtocolMappers', 'listIamProviderInterfaces', 'listIamPushedAuthorizationRequests',
  'listIamRealmAttributes', 'listIamRealmBindings', 'listIamRealmBrokers', 'listIamRealmExports', 'listIamRealmTemplates',
  'listIamRealms', 'listIamResilienceRuns', 'listIamResourceServers', 'listIamRestoreRecords',
  'listIamRoles', 'listIamSamlSessions', 'listIamSecurityEvents', 'listIamServiceAccounts',
  'listIamSigningKeys', 'listIamTokenExchanges', 'listIamUserFederationProviders',
  'listIamUserProfileSchemas', 'listIamUsers', 'listIamWebAuthnCredentials', 'login',
  'loginIamBroker', 'loginIamBrowser', 'loginIamSaml', 'logout', 'logoutIamAccount',
  'previewIamNotificationTemplate', 'recordIamFormalReview', 'regenerateIamBootstrapPackage',
  'requestIamAccountDelegatedConsent', 'requestIamEmailVerification', 'requestIamPasswordReset',
  'resetIamUserPassword', 'restoreIamBackup', 'revokeIamAccountDelegatedConsent',
  'deleteIamRealmAttribute',
  'revokeIamAccountSession', 'revokeIamAccountWebAuthnCredential',
  'revokeIamOrganizationInvitation', 'revokeIamToken', 'revokeIamUserSessions',
  'revokeOtherIamAccountSessions', 'rotateIamClientSecret', 'rotateIamSigningKey',
  'runIamBenchmarkSuite', 'runIamRecoveryDrill', 'runIamResilienceSuite', 'selectAuthTenant',
  'sendIamTestNotification', 'syncIamUserFederationProvider', 'updateIamAccountProfile',
  'updateIamAdminPermission', 'updateIamAdminPolicy', 'updateIamAuthExecution',
  'updateIamAuthFlow', 'updateIamAuthorizationPermission', 'updateIamAuthorizationPolicy',
  'updateIamClient', 'updateIamClientAuthFlowBindings', 'updateIamClientPolicy',
  'updateIamClientScope', 'updateIamDelegatedAdmin', 'updateIamDeploymentProfile',
  'updateIamExtension', 'updateIamExtensionBinding', 'updateIamExtensionProvider',
  'updateIamGroup', 'updateIamIdentityProvider', 'updateIamNotificationTemplate',
  'updateIamOrganization', 'updateIamOrganizationMembership', 'updateIamProtectedResource',
  'updateIamProtectedScope', 'updateIamProtocolMapper', 'updateIamRealm', 'updateIamRealmAttribute',
  'updateIamRealmAuthFlowBindings', 'updateIamRealmBinding', 'updateIamRealmLocalization',
  'updateIamRealmTheme', 'updateIamResourceServer', 'updateIamRole', 'updateIamUser',
  'updateIamUserFederationProvider', 'updateIamUserProfileSchema',
  'verifyIamDeviceAuthorization', 'verifyIamLoginMfa', 'verifyIamMfaEnrollment',
] as const

export type StandaloneIdpApiMethodName = (typeof standaloneIdpApiMethodNames)[number]
export type StandaloneIdpApi = Pick<typeof compatIdpApi, StandaloneIdpApiMethodName>

export const idpApi: StandaloneIdpApi = Object.fromEntries(
  standaloneIdpApiMethodNames.map((methodName) => [methodName, compatIdpApi[methodName]] as const),
) as StandaloneIdpApi
