#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
ENV_LABEL="${IDP_ENV_LABEL:-default}"
DEFAULT_OUTPUT_DIR="${ROOT_DIR}/tmp/runtime-cutover-evidence/sequence-a-${ENV_LABEL}-${TIMESTAMP}"
OUTPUT_DIR="${1:-${DEFAULT_OUTPUT_DIR}}"
PARENT_README="${OUTPUT_DIR}/README.md"
MANIFEST_JSON="${OUTPUT_DIR}/sequence-a-manifest.json"
STATUS_MATRIX_MD="${OUTPUT_DIR}/sequence-a-status-matrix.md"
VERIFY_SUMMARY_MD="${OUTPUT_DIR}/sequence-a-verification.md"
VERIFY_SUMMARY_JSON="${OUTPUT_DIR}/sequence-a-verification.json"

mkdir -p "${OUTPUT_DIR}"

run_step() {
  local slug="$1"
  local step_number="$2"
  local entity_family="$3"
  local checklist_path="$4"
  local target_dir="${OUTPUT_DIR}/${slug}"

  echo "Preparing Sequence A evidence bundle for ${entity_family}..."
  bash "${ROOT_DIR}/scripts/prepare-idp-runtime-cutover-evidence.sh" \
    "${slug}" \
    "${step_number}" \
    "${entity_family}" \
    "${checklist_path}" \
    "${target_dir}"
}

run_step "login-transactions" "1" "Login transactions" "docs/spec/plans/Headless_IAM_Login_Transaction_Cutover_Checklist.md"
run_step "tickets" "2" "Tickets" "docs/spec/plans/Headless_IAM_Ticket_Cutover_Checklist.md"
run_step "sessions" "3" "Sessions" "docs/spec/plans/Headless_IAM_Session_Cutover_Checklist.md"
run_step "issued-tokens" "4" "Issued tokens" "docs/spec/plans/Headless_IAM_Issued_Token_Cutover_Checklist.md"

cat > "${PARENT_README}" <<EOF
# Sequence A Evidence Bundle

Generated by \`bash scripts/prepare-idp-sequence-a-evidence.sh\`.

Environment inputs:

- \`IDP_BASE_URL\`: target environment base URL used for preflight and auth bootstrap
- \`IDP_ENV_LABEL\`: optional environment label included in the bundle path
- \`IDP_IAM_REALM_ID\`: optional explicit realm override for API-only environments
- \`IDP_IAM_CLIENT_ID\`: optional explicit client override for API-only environments
- \`IDP_ADMIN_EMAIL\`: optional admin email used during preflight authentication
- \`IDP_ADMIN_PASSWORD\`: optional admin password used during preflight authentication

Contained step bundles:

- \`login-transactions/\`: Sequence A / Step 1 bundle
- \`tickets/\`: Sequence A / Step 2 bundle
- \`sessions/\`: Sequence A / Step 3 bundle
- \`issued-tokens/\`: Sequence A / Step 4 bundle

Parent artifact index:

- \`README.md\`: this guide
- \`sequence-a-manifest.json\`: machine-readable bundle inventory
- \`sequence-a-status-matrix.md\`: top-level execution status and Phase 1 go/no-go surface
- \`sequence-a-verification.md\`: latest human-readable completeness check
- \`sequence-a-verification.json\`: latest machine-readable completeness check

Per-step artifact map:

- \`login-transactions/\`
  - \`login-transactions-preflight.json\`
  - \`operations-health.json\`
  - \`login-transactions-preflight.md\`
  - \`login-transactions-live-evidence.md\`
  - \`README.md\`
- \`tickets/\`
  - \`tickets-preflight.json\`
  - \`operations-health.json\`
  - \`tickets-preflight.md\`
  - \`tickets-live-evidence.md\`
  - \`README.md\`
- \`sessions/\`
  - \`sessions-preflight.json\`
  - \`operations-health.json\`
  - \`sessions-preflight.md\`
  - \`sessions-live-evidence.md\`
  - \`README.md\`
- \`issued-tokens/\`
  - \`issued-tokens-preflight.json\`
  - \`operations-health.json\`
  - \`issued-tokens-preflight.md\`
  - \`issued-tokens-live-evidence.md\`
  - \`README.md\`

Recommended operator flow:

1. Confirm each step bundle preflight shows \`runtime_cutover_status=PASS\` and does not report \`NOOP_FALLBACK\`.
2. Execute each checklist in order, recording Stage 0, Stage 1, Stage 2, and rollback evidence in the generated markdown.
3. Attach raw logs or direct storage proof alongside the matching step bundle.
4. Regenerate \`sequence-a-status-matrix.md\` if bundle contents change materially during review.
5. Run the bundle completeness verifier and treat any non-zero exit as a signal that the packet still contains unresolved scaffold placeholders or missing artifacts.
6. Produce a go/no-go summary after all four bundles are complete.

Generated artifacts:

- \`README.md\`: parent bundle guide
- \`sequence-a-manifest.json\`: machine-readable summary of the bundle layout
- \`sequence-a-status-matrix.md\`: formal top-level status and decision document for the execution window
- \`sequence-a-verification.md\`: latest human-readable completeness check result
- \`sequence-a-verification.json\`: latest machine-readable completeness check result

Useful follow-up commands:

- \`npm run render:idp:sequence-a-status-matrix -- "${MANIFEST_JSON}" > "${STATUS_MATRIX_MD}"\`
- \`npm run verify:idp:sequence-a-bundle -- "${MANIFEST_JSON}"\`
- \`OUTPUT_MODE=json npm run verify:idp:sequence-a-bundle -- "${MANIFEST_JSON}"\`
- \`OUTPUT_MODE=markdown npm run verify:idp:sequence-a-bundle -- "${MANIFEST_JSON}" > "${VERIFY_SUMMARY_MD}"\`

Verifier interpretation:

- exit code \`0\`: parent status matrix and all step evidence documents are free of scaffold placeholders and the packet is review-ready
- non-zero exit: at least one expected artifact is missing or still contains unresolved \`<fill>\` placeholders
EOF

cat > "${MANIFEST_JSON}" <<EOF
{
  "manifest_kind": "idp-sequence-a-bundle",
  "manifest_version": 1,
  "generated_at": "${TIMESTAMP}",
  "environment_label": "${ENV_LABEL}",
  "bundle_status": "scaffolded",
  "output_dir": "${OUTPUT_DIR}",
  "parent_readme": "${PARENT_README}",
  "status_matrix_markdown": "${STATUS_MATRIX_MD}",
  "verification_markdown": "${VERIFY_SUMMARY_MD}",
  "verification_json": "${VERIFY_SUMMARY_JSON}",
  "parent_artifacts": {
    "readme": "${PARENT_README}",
    "manifest_json": "${MANIFEST_JSON}",
    "status_matrix_markdown": "${STATUS_MATRIX_MD}",
    "verification_markdown": "${VERIFY_SUMMARY_MD}",
    "verification_json": "${VERIFY_SUMMARY_JSON}"
  },
  "steps": [
    {
      "slug": "login-transactions",
      "step_number": 1,
      "entity_family": "Login transactions",
      "output_dir": "${OUTPUT_DIR}/login-transactions",
      "artifacts": {
        "preflight_json": "${OUTPUT_DIR}/login-transactions/login-transactions-preflight.json",
        "operations_health_json": "${OUTPUT_DIR}/login-transactions/operations-health.json",
        "preflight_markdown": "${OUTPUT_DIR}/login-transactions/login-transactions-preflight.md",
        "live_evidence_markdown": "${OUTPUT_DIR}/login-transactions/login-transactions-live-evidence.md",
        "readme": "${OUTPUT_DIR}/login-transactions/README.md"
      }
    },
    {
      "slug": "tickets",
      "step_number": 2,
      "entity_family": "Tickets",
      "output_dir": "${OUTPUT_DIR}/tickets",
      "artifacts": {
        "preflight_json": "${OUTPUT_DIR}/tickets/tickets-preflight.json",
        "operations_health_json": "${OUTPUT_DIR}/tickets/operations-health.json",
        "preflight_markdown": "${OUTPUT_DIR}/tickets/tickets-preflight.md",
        "live_evidence_markdown": "${OUTPUT_DIR}/tickets/tickets-live-evidence.md",
        "readme": "${OUTPUT_DIR}/tickets/README.md"
      }
    },
    {
      "slug": "sessions",
      "step_number": 3,
      "entity_family": "Sessions",
      "output_dir": "${OUTPUT_DIR}/sessions",
      "artifacts": {
        "preflight_json": "${OUTPUT_DIR}/sessions/sessions-preflight.json",
        "operations_health_json": "${OUTPUT_DIR}/sessions/operations-health.json",
        "preflight_markdown": "${OUTPUT_DIR}/sessions/sessions-preflight.md",
        "live_evidence_markdown": "${OUTPUT_DIR}/sessions/sessions-live-evidence.md",
        "readme": "${OUTPUT_DIR}/sessions/README.md"
      }
    },
    {
      "slug": "issued-tokens",
      "step_number": 4,
      "entity_family": "Issued tokens",
      "output_dir": "${OUTPUT_DIR}/issued-tokens",
      "artifacts": {
        "preflight_json": "${OUTPUT_DIR}/issued-tokens/issued-tokens-preflight.json",
        "operations_health_json": "${OUTPUT_DIR}/issued-tokens/operations-health.json",
        "preflight_markdown": "${OUTPUT_DIR}/issued-tokens/issued-tokens-preflight.md",
        "live_evidence_markdown": "${OUTPUT_DIR}/issued-tokens/issued-tokens-live-evidence.md",
        "readme": "${OUTPUT_DIR}/issued-tokens/README.md"
      }
    }
  ]
}
EOF

node "${ROOT_DIR}/scripts/render-idp-sequence-a-status-matrix.js" "${MANIFEST_JSON}" > "${STATUS_MATRIX_MD}"
node "${ROOT_DIR}/scripts/update-idp-sequence-a-bundle-status.js" "${MANIFEST_JSON}" >/dev/null
node "${ROOT_DIR}/scripts/render-idp-sequence-a-status-matrix.js" "${MANIFEST_JSON}" > "${STATUS_MATRIX_MD}"
OUTPUT_MODE=markdown node "${ROOT_DIR}/scripts/verify-idp-sequence-a-bundle.js" "${MANIFEST_JSON}" > "${VERIFY_SUMMARY_MD}" || true
OUTPUT_MODE=json node "${ROOT_DIR}/scripts/verify-idp-sequence-a-bundle.js" "${MANIFEST_JSON}" > "${VERIFY_SUMMARY_JSON}" || true

cat <<EOF
sequence_a_output_dir=${OUTPUT_DIR}
sequence_a_readme=${PARENT_README}
sequence_a_manifest_json=${MANIFEST_JSON}
sequence_a_status_matrix_markdown=${STATUS_MATRIX_MD}
sequence_a_verification_markdown=${VERIFY_SUMMARY_MD}
sequence_a_verification_json=${VERIFY_SUMMARY_JSON}
sequence_a_verify_command=npm run verify:idp:sequence-a-bundle -- "${MANIFEST_JSON}"
sequence_a_render_status_matrix_command=npm run render:idp:sequence-a-status-matrix -- "${MANIFEST_JSON}" '>' "${STATUS_MATRIX_MD}"
sequence_a_update_status_command=npm run update:idp:sequence-a-bundle-status -- "${MANIFEST_JSON}"
login_transactions_dir=${OUTPUT_DIR}/login-transactions
tickets_dir=${OUTPUT_DIR}/tickets
sessions_dir=${OUTPUT_DIR}/sessions
issued_tokens_dir=${OUTPUT_DIR}/issued-tokens
generated_at=${TIMESTAMP}
environment_label=${ENV_LABEL}
EOF
