#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [[ $# -lt 4 || $# -gt 5 ]]; then
  echo "Usage: bash scripts/prepare-idp-runtime-cutover-evidence.sh <slug> <step-number> <entity-family> <checklist-path> [output-dir]" >&2
  exit 1
fi

SLUG="$1"
STEP_NUMBER="$2"
ENTITY_FAMILY="$3"
CHECKLIST_PATH="$4"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
ENV_LABEL="${IDP_ENV_LABEL:-default}"
DEFAULT_OUTPUT_DIR="${ROOT_DIR}/tmp/runtime-cutover-evidence/${SLUG}-${ENV_LABEL}-${TIMESTAMP}"
OUTPUT_DIR="${5:-${DEFAULT_OUTPUT_DIR}}"

mkdir -p "${OUTPUT_DIR}"

PREFLIGHT_JSON="${OUTPUT_DIR}/${SLUG}-preflight.json"
HEALTH_RESPONSE_JSON="${OUTPUT_DIR}/operations-health.json"
PREFLIGHT_MD="${OUTPUT_DIR}/${SLUG}-preflight.md"
EVIDENCE_MD="${OUTPUT_DIR}/${SLUG}-live-evidence.md"
BUNDLE_README="${OUTPUT_DIR}/README.md"

echo "Capturing runtime cutover preflight JSON..."
OUTPUT_MODE=json node "${ROOT_DIR}/scripts/verify-idp-runtime-cutover-readiness.js" > "${PREFLIGHT_JSON}"

echo "Extracting raw health response artifact..."
jq '.health_response' "${PREFLIGHT_JSON}" > "${HEALTH_RESPONSE_JSON}"

echo "Rendering runtime cutover preflight markdown..."
node "${ROOT_DIR}/scripts/render-idp-runtime-cutover-preflight.js" "${PREFLIGHT_JSON}" > "${PREFLIGHT_MD}"

echo "Scaffolding live evidence markdown..."
node "${ROOT_DIR}/scripts/scaffold-idp-runtime-cutover-evidence.js" \
  "${PREFLIGHT_JSON}" \
  "${STEP_NUMBER}" \
  "${ENTITY_FAMILY}" \
  "${CHECKLIST_PATH}" \
  > "${EVIDENCE_MD}"

cat > "${BUNDLE_README}" <<EOF
# ${ENTITY_FAMILY} Evidence Bundle

Generated by \`bash scripts/prepare-idp-runtime-cutover-evidence.sh\`.

Environment inputs:

- \`IDP_BASE_URL\`: target environment base URL for preflight and auth bootstrap
- \`IDP_ENV_LABEL\`: optional environment label included in the output directory name
- \`IDP_IAM_REALM_ID\`: optional explicit realm override for API-only environments
- \`IDP_IAM_CLIENT_ID\`: optional explicit client override for API-only environments
- \`IDP_ADMIN_EMAIL\`: optional admin email used during preflight authentication
- \`IDP_ADMIN_PASSWORD\`: optional admin password used during preflight authentication

Included artifacts:

- \`$(basename "${PREFLIGHT_JSON}")\`: structured runtime cutover preflight JSON
- \`$(basename "${HEALTH_RESPONSE_JSON}")\`: raw \`/api/v1/iam/operations/health\` response captured from the preflight
- \`$(basename "${PREFLIGHT_MD}")\`: rendered preflight markdown section
- \`$(basename "${EVIDENCE_MD}")\`: scaffolded live evidence document for \`Sequence A / Step ${STEP_NUMBER}\`

Recommended next actions:

1. If preflight capture failed, rerun with \`IDP_BASE_URL\` pointed at the running target environment.
2. Review the preflight JSON and markdown to confirm the environment is not reporting \`NOOP_FALLBACK\`.
3. Open the scaffolded evidence markdown and fill in:
   - target environment
   - operator
   - runtime build / commit
   - runtime table name
4. Execute the checklist referenced by \`${CHECKLIST_PATH}\` across Stage 0, Stage 1, and Stage 2.
5. Record rollback results and final go/no-go status for the next step.
6. Attach any raw logs or direct storage evidence gathered during the run.
EOF

cat <<EOF
preflight_json=${PREFLIGHT_JSON}
health_response_json=${HEALTH_RESPONSE_JSON}
preflight_markdown=${PREFLIGHT_MD}
evidence_markdown=${EVIDENCE_MD}
bundle_readme=${BUNDLE_README}
environment_label=${ENV_LABEL}
generated_at=${TIMESTAMP}
output_dir=${OUTPUT_DIR}
EOF
