#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
ENV_LABEL="${IDP_ENV_LABEL:-default}"
DEFAULT_OUTPUT_DIR="${ROOT_DIR}/tmp/runtime-distributed-bundle/${ENV_LABEL}-${TIMESTAMP}"
OUTPUT_DIR="${1:-${DEFAULT_OUTPUT_DIR}}"

mkdir -p "${OUTPUT_DIR}"

BUNDLE_JSON="${ROOT_DIR}/tests/integration/latest-runtime-distributed-bundle.json"
VERIFICATION_JSON="${ROOT_DIR}/tests/integration/latest-runtime-distributed-bundle-verification.json"
SUMMARY_MD="${OUTPUT_DIR}/runtime-distributed-bundle-summary.md"
BUNDLE_COPY="${OUTPUT_DIR}/runtime-distributed-bundle.json"
VERIFICATION_COPY="${OUTPUT_DIR}/runtime-distributed-bundle-verification.json"
TEST_REPORT_MD="${ROOT_DIR}/test-results-report.md"
TEST_REPORT_JSON="${ROOT_DIR}/test-results-report.json"
TEST_REPORT_MD_COPY="${OUTPUT_DIR}/test-results-report.md"
TEST_REPORT_JSON_COPY="${OUTPUT_DIR}/test-results-report.json"
LOGS_DIR="${ROOT_DIR}/tests/integration/runtime-distributed-bundle-logs"
LOGS_COPY_DIR="${OUTPUT_DIR}/runtime-distributed-bundle-logs"
BUNDLE_README="${OUTPUT_DIR}/README.md"

echo "Running full distributed runtime bundle verification..."
npm run verify:idp:runtime-distributed-bundle-full

if [[ ! -f "${BUNDLE_JSON}" ]]; then
  echo "Expected bundle JSON was not produced: ${BUNDLE_JSON}" >&2
  exit 1
fi

if [[ ! -f "${VERIFICATION_JSON}" ]]; then
  echo "Expected verification JSON was not produced: ${VERIFICATION_JSON}" >&2
  exit 1
fi

cp "${BUNDLE_JSON}" "${BUNDLE_COPY}"
cp "${VERIFICATION_JSON}" "${VERIFICATION_COPY}"

if [[ -d "${LOGS_DIR}" ]]; then
  rm -rf "${LOGS_COPY_DIR}"
  cp -R "${LOGS_DIR}" "${LOGS_COPY_DIR}"
fi

echo "Rendering distributed runtime bundle markdown summary..."
node "${ROOT_DIR}/scripts/render-runtime-distributed-bundle-summary.js" "${VERIFICATION_COPY}" > "${SUMMARY_MD}"

echo "Refreshing consolidated repo test report..."
node "${ROOT_DIR}/scripts/report-test-results.mjs" > /dev/null

if [[ ! -f "${TEST_REPORT_MD}" || ! -f "${TEST_REPORT_JSON}" ]]; then
  echo "Expected consolidated test report artifacts were not produced." >&2
  exit 1
fi

cp "${TEST_REPORT_MD}" "${TEST_REPORT_MD_COPY}"
cp "${TEST_REPORT_JSON}" "${TEST_REPORT_JSON_COPY}"

cat > "${BUNDLE_README}" <<EOF
# Runtime Distributed Bundle Evidence

Generated by \`bash scripts/prepare-runtime-distributed-bundle-evidence.sh\`.

Environment inputs:

- \`IDP_ENV_LABEL\`: optional environment label included in the output directory name
- distributed-runtime environment variables used by \`verify:idp:runtime-distributed-bundle-full\`

Included artifacts:

- \`$(basename "${BUNDLE_COPY}")\`: raw distributed runtime bundle execution output
- \`$(basename "${VERIFICATION_COPY}")\`: verifier output for the distributed runtime bundle
- \`$(basename "${SUMMARY_MD}")\`: rendered markdown summary for operator review
- \`$(basename "${TEST_REPORT_MD_COPY}")\`: repo-level test status report at evidence capture time
- \`$(basename "${TEST_REPORT_JSON_COPY}")\`: repo-level machine-readable test status report at evidence capture time
- \`$(basename "${LOGS_COPY_DIR}")/\`: per-step distributed bundle execution logs, if the bundle runner produced them

Recommended next actions:

1. Review the verifier summary and confirm \`overall_pass=true\`.
2. Confirm the copied repo-level test report matches the expected cutover review window.
3. Review the copied per-step logs for any failed or slow step before deciding on rerun vs remediation.
4. If any artifact is stale or missing, rerun this preparer rather than reusing partial outputs.
5. Attach this bundle to release, cutover, or runtime-readiness review.
EOF

cat <<EOF
bundle_json=${BUNDLE_COPY}
verification_json=${VERIFICATION_COPY}
summary_markdown=${SUMMARY_MD}
test_report_markdown=${TEST_REPORT_MD_COPY}
test_report_json=${TEST_REPORT_JSON_COPY}
bundle_logs_dir=${LOGS_COPY_DIR}
bundle_readme=${BUNDLE_README}
environment_label=${ENV_LABEL}
generated_at=${TIMESTAMP}
output_dir=${OUTPUT_DIR}
EOF
